{% set name = "py_entitymatching" %}
{% set pypi_name = name | replace ('_', '-') %}
{% set version = "0.4.2" %}
{% set sha256 = "3656a8ab0bdce297ed3ae13c890c0091deeae79367aad44e3f84effd44b60f7f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msinttypes  # [vc9]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy {{ numpy }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - pandas
    - joblib
    - pyprind
    - py_stringsimjoin >=0.3.0
    - cloudpickle >=0.2.1
    - pyparsing >=2.1.4
    - scikit-learn >=0.22
    - requests
    - ipython >=5.6
    - matplotlib-base >=2.2.4
    - scipy

test:
  source_files:
    - py_entitymatching/tests
  imports:
    - py_entitymatching
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # skip test_null_cases, marked @unittest.skip("Not a test")
    - pytest -v py_entitymatching/tests -k "not test_null_cases"

about:
  home: https://sites.google.com/site/anhaidgroup/current-projects/magellan/py_entitymatching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for entity matching.
  description: |
    This project seeks to build a Python software package to match entities
    between two tables using supervised learning. 
  doc_url: https://anhaidgroup.github.io/py_entitymatching/
  dev_url: https://github.com/anhaidgroup/py_entitymatching

extra:
  recipe-maintainers:
    - pjmartinkus
