# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hYjT1xohxGIG4s0+vWGRyCMtpenWfgRw7aIV83KX5ACUfjvpJseJC+IqbISJ56YJXEx5dQACbM5lGiXHfKxWlnFuL0uQA0C+lgU4pTZZJpKOW/wospyD6AiTdCRpKPNYKt1tHYkfq1E0ELBsetLi7PcujqxjrjTRmPwHdYFVkkgIGfAccp0FiPiU8EBNNd0LL/oFIjscu+sA9KxHVK4PSTKyE6ja+LvWi89/3c/HDP+g+QibkMA7JQrulZzeMJL0wNcbHibuWiQ+iUrE2YSOtSZ9nlT3cwSndoVYvbM8KoTplBorImU4a1eYk6IJe8Cr9TegSozKegQGCPlH6eA7cE7JLoqSUgGGG+UEW9WHL1UwzDu0j+zGj58xPFUwXyi8cl0GSFl6tYo4owOpW12+95CU4SiWUfTbN8FPp87QyNF+Jhy92Gg/rpwod9gu2L8ppgRuv4M5IdGj/P+snRv35q9nD38/oAzc5rnHf8eE38g34IkmiFpcgAbztZUrFU67DuuyXQBdHDMZULR7hMhCKRKx9Ogj/moWH1x68hyzmDiqD7lM4SiS51f5TeWl74WNn0gA8qUqc5DNeupFClO5kkJq8pCSQ+LGrXNoYfKmveh5Is++Kj+yr1T8SEw5n/ILlOqRUS11+btESdEOwJHGnAHWCmifBO47hfHAzIwKYAk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
