travis:
  secure:
    BINSTAR_TOKEN: VSIsR7U26S4OVftdnLv9LvAHQ5X0FxbvtNXNlLqdhDS9oTA4l4s44/R5r8uNiYwzDnGuCg1TS0/Ncpt3lmqOmIgBpg7tpK91tIVUTYG7OshRxi1fFk/T5uxca5hlAfEUl2OjjgdUG+mNTybYzD8AUWm8YCGSCB2MBhMGN0hw6Fs3m5bZx4+1GWizifPbB9/Oc6zzYO96RHxDlHbdVqw0XuE8uDxNoRAmVKxkYkSS55DZAWGvT0hyP5n1+vpo+CCQy9XzmAQiEhIq/EO3POmpp4MvMTu14q912PuKd8/3ujOJtjW8Cw135JGfStVLvCaJPo9te2Pwb7/Wkt5+2AMwRk5eUPXpHIiNLp9cL4zqHHlybwMx5XVKT7xQPgJmOBCvdLvzHvUpl8rPKCIEzkk/+4Dor1zKaXnt8x/+f8m3kWq8N6gElCEhKiXVt/JWTKPBLMOLSyZ5fVMhatAZ41BQBN3rVYx9eLqz1St0+9ZmWz0DBpTPtHKDivxzjQ65/oM3YBApnvUIPj3zv0hgZIQNBweffPQLVIE1mhXiyJpyB+kxpH77UQk5FB7DVnaWcqMlpehSAgT9Ljyw/nwSsw5myRMfdunmGtC0mv/aFAbFfRfAAXlipfpdCW1xfj47UI/uMTGD99q1EO6OyxcbNDNZRo5C/aINhIYt/oNUNM2TjqU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
