travis:
  secure:
    BINSTAR_TOKEN: hYjT1xohxGIG4s0+vWGRyCMtpenWfgRw7aIV83KX5ACUfjvpJseJC+IqbISJ56YJXEx5dQACbM5lGiXHfKxWlnFuL0uQA0C+lgU4pTZZJpKOW/wospyD6AiTdCRpKPNYKt1tHYkfq1E0ELBsetLi7PcujqxjrjTRmPwHdYFVkkgIGfAccp0FiPiU8EBNNd0LL/oFIjscu+sA9KxHVK4PSTKyE6ja+LvWi89/3c/HDP+g+QibkMA7JQrulZzeMJL0wNcbHibuWiQ+iUrE2YSOtSZ9nlT3cwSndoVYvbM8KoTplBorImU4a1eYk6IJe8Cr9TegSozKegQGCPlH6eA7cE7JLoqSUgGGG+UEW9WHL1UwzDu0j+zGj58xPFUwXyi8cl0GSFl6tYo4owOpW12+95CU4SiWUfTbN8FPp87QyNF+Jhy92Gg/rpwod9gu2L8ppgRuv4M5IdGj/P+snRv35q9nD38/oAzc5rnHf8eE38g34IkmiFpcgAbztZUrFU67DuuyXQBdHDMZULR7hMhCKRKx9Ogj/moWH1x68hyzmDiqD7lM4SiS51f5TeWl74WNn0gA8qUqc5DNeupFClO5kkJq8pCSQ+LGrXNoYfKmveh5Is++Kj+yr1T8SEw5n/ILlOqRUS11+btESdEOwJHGnAHWCmifBO47hfHAzIwKYAk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
